### PR TITLE
Getting started

### PR DESCRIPTION
**Pull request by geoglrb**

### CODE REVIEW

**Comment by geoglrb** [comment]
hi! So, @nicklally made the good point to me that my above commit isn't really appropriate to this branch, and he's totally right! But since I went there on the way to working on the gettingStarted issues, I guess we'll leave it here (and he'll improve on it in a minute...)

Just wanted to ask, @lfunke, if the code I commented out in the above commit was indeed superfluous at this point. I think it was? This part, from `gisUI.js`:
```//var values = document.getElementById("values");
//colorPicker.on(["color:init", "color:change"], function(color, values){
//  var hexPicker = colorPicker.color.hexString;
//  console.log(hexPicker);
//  values.innerHTML = [
//    "hex: " + color.hexString,
//  ].join("<br>");
//});```

**Comment by lfunke** [comment]
> hi! So, @nicklally made the good point to me that my above commit isn't really appropriate to this branch, and he's totally right! But since I made it (and, now this comment) on the way to working on the gettingStarted issues, I guess we can just leave it here (and Nick will further improve on it in a minute...). My apologies--I will try not to do this again! :)
> 
> Just wanted to ask, @lfunke, if the code I commented out in the above commit was indeed superfluous at this point. I think it was? This part, from `gisUI.js`:
> 
> ```
> //var values = document.getElementById("values");
> //colorPicker.on(["color:init", "color:change"], function(color, values){
> //  var hexPicker = colorPicker.color.hexString;
> //  console.log(hexPicker);
> //  values.innerHTML = [
> //    "hex: " + color.hexString,
> //  ].join("<br>");
> //});
> ```

Seems to be working just fine, @geoglrb ! Thanks for checking in.

**Comment by nicklally** [comment]
I'm done making changes to this branch, so happy to merge with everyone's approval

**Comment by lfunke** [comment]
this all looks great! I hope you both enjoy NACIS, and I look forward to talking afterwards.

**Comment by geoglrb** [comment]
Wow, thanks, all!
This is so pleasing...

@nicklally and I just discussed merging, so I'll do it.

**Pull request merged**
