### PR TITLE
UI minor changes

### PR DESCRIPTION
**Pull request by lfunke**
In this new branch, I have started incorporating small UI changes I made to my local version. 
1. Tooltips for context on EDIT, RENDER, FOCUS, RESET buttons. Adjust text as needed. (More to come)
2. I added the current # of nodes to the Bind alert error message so that users can see which map is missing nodes and successfully bind their two maps. 
3. I incorporated a list of file types to canvas load message.

### CODE REVIEW

**Comment by geoglrb** [comment]
Wow, fabulous! Thanks so much for all this. I missed the request. I'll look at it soon.

**Comment by lfunke** [comment]
Just found an issue with the last commit- the focus button in the render canvas. The current function swaps users back to single map mode when clicked. One solution could be to listen for a change to the 2 map mode check box and disabling the focus function accordingly. Other ideas?

**Comment by nicklally** [comment]
Why does the focus button appear in the render canvas? Not sure what it would do there.

**Comment by lfunke** [comment]
I added the focus button there so that users can switch and view each of their maps individually without having to go back to the edit menú. I found as I was exporting graphics it was tedious to switch over to the edit mode to focus on a different map, so I thought up a solution. This seemed like the most streamlined way.

________________________________

**Comment by lfunke** [comment]
> Why does the focus button appear in the render canvas? Not sure what it would do that

I added the focus button there so that users can switch and view each of their maps individually without having to go back to the edit menú. I found as I was exporting graphics it was tedious to switch over to the edit mode to focus on a different map, so I thought up a solution. This seemed like the most streamlined way. I resolved the issue above by editing the wormMode menu to hide the button when I user selects 2 map mode

**Pull request merged**
